name: Production
run-name: ${{ github.event.workflow_run.display_title || 'Production' }}

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Non-Production
    types:
      - completed
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: false

# For reusable workflows, the permissions setting for id-token should be set to write at the
# caller workflow level or in the specific job that calls the reusable workflow.

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  regional:
    name: "Regional: ${{ matrix.zone }}"
    uses: osinfra-io/pt-techne-opentofu-workflows/.github/workflows/plan-and-apply.yml@66e04fe1c5a017238caf7be3d544a0a66b918dd1 # v0.5.5
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_commit.author.name != 'dependabot[bot]')
    strategy:
      matrix:
        include:
          - zone: us-east1-b
          - zone: us-east4-a
    with:
      checkout_ref: ${{ github.event.workflow_run.head_sha || github.sha }}
      github_environment: "Production: ${{ matrix.zone }}"
      opentofu_kms_encryption_key: projects/pt-corpus-tf16-prod/locations/us/keyRings/state-encryption/cryptoKeys/default
      opentofu_state_bucket: pt-kryptos-state-prod
      opentofu_version: ${{ vars.OPENTOFU_VERSION }}
      opentofu_workspace: ${{ matrix.zone }}-production
      service_account: pt-kryptos-github@pt-corpus-tf16-prod.iam.gserviceaccount.com
      working_directory: regional
      workload_identity_provider: projects/557265520053/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc
